name: 'housamoAutoLogin'
 
on:
  schedule:
    - cron: '0 */12 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: pip install requests
    - name: Read anth_key from secrets  #读取账号
      env: 
        auth_key: ${{ secrets.AUTH_KEY }} # secrets 提供
    - name: Login #登录
      run: python Login.py
