name: 'housamoAutoLogin'

on:
  schedule:
    - cron: '0  0,7,15,23 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: pip install requests
    - name: Read anth_key & Login  #读取账号并登录
      env: 
        auth_keys: ${{ toJson(secrets) }}   # 由secrets 提供auth_key
      run: echo "${AUTHKEY_MORONG}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter 5 -k "abcd"
           
           
