name: 'housamoAutoLogin'

on:
  schedule:
    - cron: '0  14,23 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: pip install requests
    - name: Read anth_key & Login  #读取账号并登录
      env: 
        auth_keys: ${{ toJson(secrets) }}   # 由secrets 提供auth_key
      run: python Login.py
    - name: Commit & Push  #更新仓库保持活跃
      run: |
        git config --global user.email 243304341@qq.com
        git config --global user.name dandan
        git add .
        git commit -m "action update"
        git pull --rebase
        use: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.Action}}
